## Getting Started
I will start by generating a fake dataset that has lots of features (like a single-cell RNA sequence data), and from there we will cover how to properly scale and reduce this dataset using python.

In [1]:
import numpy as np
import pandas as pd
import umap ###install with "pip install umap-learn"
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

In [2]:
''' Sample single cell RNA sequence dataset (or any dataset that has lots and lots of features really) '''
data = np.random.rand(100,1000)
datacols = ["gene " + str(i) for i in range(1000)]
datainds = ["cell " + str(i) for i in range(100)]


''''I use a dataframe here because (I) it's nice to see the names of indicies and columns and 
(II) I find them easier to manipulate than arrays
'''
data = pd.DataFrame(data,index=datainds,columns=datacols)

print(data)

           gene 0    gene 1    gene 2    gene 3    gene 4    gene 5    gene 6  \
cell 0   0.361956  0.905231  0.563989  0.407784  0.565950  0.667291  0.199240   
cell 1   0.568309  0.150535  0.241002  0.410562  0.726471  0.323721  0.715482   
cell 2   0.559112  0.036849  0.505173  0.779751  0.662385  0.154056  0.473187   
cell 3   0.652772  0.369879  0.693575  0.778016  0.825892  0.355109  0.885646   
cell 4   0.633109  0.689327  0.457349  0.673912  0.163530  0.596780  0.649866   
...           ...       ...       ...       ...       ...       ...       ...   
cell 95  0.716973  0.092316  0.410624  0.700065  0.950595  0.341745  0.969039   
cell 96  0.467488  0.439938  0.735292  0.544692  0.550801  0.519355  0.701676   
cell 97  0.850052  0.861149  0.876526  0.910968  0.682121  0.194139  0.173512   
cell 98  0.054695  0.236842  0.038705  0.095301  0.912898  0.043637  0.768782   
cell 99  0.887433  0.897868  0.975519  0.169719  0.919159  0.432399  0.493379   

           gene 7    gene 8

## Scaling

In our example, we will use normalization. Normalization, as we know, is a safer bet than standardization because the features do not need to be Gaussian. Standardization code looks the same, but uses the StandardScaler not the minmax scaler. 

In [3]:
'''

Scaling: Normalization used in this example.
Standardization looks the same, just uses the StandardScaler not the MinMaxScaler

'''

####Uses the values function of pandas - converts any dataframe to an array
data_for_scaling = data.values

#### the scaling object
scaler = MinMaxScaler()


''' 
We will use fit_transform here - we want to actually scale this data, not use the scaler on a different dataset
'''

scaled_data = scaler.fit_transform(data_for_scaling)

## Dimensionality Reduction (UMAP)
We will start with UMAP, so you can see how to properly implement this algorithm and see what the results are supposed to look like. UMAP is an excellent approach for dimensionality reduction applied before unsupervised learning (clustering). 

In [4]:
''' --------------- UMAP CASE (no fancy customizations) ---------------- '''


data_reducer = umap.UMAP()


''' 
We will use fit_transform here again - we want to actually reduce this data, not use the UMAP model on a different dataset
'''
umap_data = data_reducer.fit_transform(scaled_data)


''' now, we will scale the low-dimensional data to prepare it for machine learning algorithms
We will use our scaler from before 
'''

scaled_umap_data = scaler.fit_transform(umap_data)
print(scaled_umap_data)

[[0.23819226 0.42139053]
 [0.911791   0.5912813 ]
 [0.74350315 0.69172394]
 [0.64326936 0.08310986]
 [0.99999994 0.8769386 ]
 [0.89912516 0.87151265]
 [0.32646757 0.5117258 ]
 [0.551078   0.11726898]
 [0.960267   0.39005947]
 [0.09743845 0.48541057]
 [0.14729273 0.3718853 ]
 [0.8927565  0.4977826 ]
 [0.34082216 0.65192604]
 [0.81916374 0.586306  ]
 [0.21530694 0.9311055 ]
 [0.66252714 0.6165706 ]
 [0.7957179  0.21753651]
 [0.36900645 0.32502365]
 [0.47281128 0.93538296]
 [0.78341705 0.77168727]
 [0.25483948 0.84025955]
 [0.37932116 0.7224705 ]
 [0.33996207 0.06217241]
 [0.96222657 0.81985784]
 [0.10447776 0.8221191 ]
 [0.67235357 0.23302019]
 [0.15114808 0.8221233 ]
 [0.9263784  0.3525945 ]
 [0.77846664 0.13337028]
 [0.         0.5349574 ]
 [0.48121732 0.1844849 ]
 [0.3715679  0.29206252]
 [0.4341138  0.12159592]
 [0.70084745 0.7614459 ]
 [0.29216737 0.6896739 ]
 [0.64291674 0.40070033]
 [0.02397263 0.7015532 ]
 [0.55570954 0.9004803 ]
 [0.2085256  0.4493736 ]
 [0.58350724 0.6872829 ]


## Dimensionality Reduction (PCA)
We will move on to PCA, so you can see how to properly implement this algorithm and see what the results are supposed to look like. PCA is an excellent approach for problems/datasets which require interpretation

In [5]:

''' ------------ PCA Case (with interpretation!!!) ------------ '''

''' We will find 4 orthogonal pricniples components here
We may need a lot more in reality - this is where experimentation is helpful! '''

data_reducer = PCA(n_components=4)

pca_data = data_reducer.fit_transform(scaled_data)
print(pca_data)


[[ 6.64189626e-01 -3.04018219e-01  1.81526454e-01  3.02044842e+00]
 [ 1.46676641e+00  1.83800369e+00  3.65212688e-01 -1.85944536e+00]
 [-2.21143750e-01 -1.08987356e-01  1.56728883e+00 -2.37055961e+00]
 [-1.08315315e+00  1.70587870e+00 -1.62891767e+00 -3.64859737e-01]
 [-4.57474466e-01 -2.01206964e-01 -8.42776768e-01  1.36722083e+00]
 [-9.38060300e-01 -4.97184101e-02  1.31392345e+00  2.35235971e-01]
 [-1.00551185e+00 -2.67801358e-01  1.33688233e+00 -6.90886771e-02]
 [-1.19348940e-02 -5.36277776e-01  1.10571522e-01 -1.40658395e+00]
 [ 1.40522794e+00  3.71935304e-01 -1.46085766e+00 -1.11835743e+00]
 [-4.64015223e-01 -2.64396692e+00  1.21260830e-01  2.40901873e+00]
 [ 1.19100560e+00 -1.04670063e+00 -1.13359516e-01  4.99859297e-01]
 [ 1.82322234e+00 -1.15521225e-02 -9.99578284e-01 -1.90714650e+00]
 [ 1.43190343e+00 -9.95779841e-01 -1.97169276e+00  1.34740113e+00]
 [-2.16343869e+00  4.40526560e-01  1.42994134e+00 -3.87460162e-01]
 [-1.15505590e+00 -6.95466450e-01  9.61200948e-01 -5.75423729e

## Interpretation of PCA results
We can use our PCA data printed above directly in our analysis. 

But we can also find the most important feature (column) in each of the principle components and use those in our analysis. In theory, this will give us the best original features for interesting, effective analysis. These features will be different internally (high variance) and externally (roughly orthogonal to the other features)

### Doing this in Sklearn
Sklearn's PCA can tell us how important each feature was for making a component. For example, to find the feature importances for the 1st principal component, use "data_reducer.components[0]"

In [6]:
''' This loop gives us the top feature of each component using the argmax function '''
top_features = [np.abs(data_reducer.components_[i]).argmax() for i in range(data_reducer.components_.shape[0])]


''' Now, we go back to our original feature names (columns of our dataset), and get the names of the 4 key features '''
top_feature_names = [list(data.columns)[top_features[i]] for i in range(data_reducer.components_.shape[0])]

''' printing the names '''
for n,name in enumerate(top_feature_names):
    print("#" + str(n) + ": " + str(name))

#0: gene 369
#1: gene 683
#2: gene 350
#3: gene 243


## Getting the features from the data
Now that we have an estimate of our features are the most important, we can pull those out of our original dataset and use them for our future analyses!

In [7]:
''' finally, extract those 4 features from the original dataset '''
newdata = data[top_feature_names]
print(newdata)

         gene 369  gene 683  gene 350  gene 243
cell 0   0.419297  0.403361  0.763053  0.967099
cell 1   0.718538  0.281815  0.590843  0.758568
cell 2   0.516610  0.901681  0.530080  0.264675
cell 3   0.423416  0.567943  0.996937  0.174476
cell 4   0.463468  0.912025  0.614511  0.893973
...           ...       ...       ...       ...
cell 95  0.401352  0.031102  0.798560  0.371557
cell 96  0.736550  0.076814  0.116702  0.700910
cell 97  0.300616  0.403744  0.291761  0.000712
cell 98  0.777189  0.138600  0.595442  0.855003
cell 99  0.207788  0.908859  0.316759  0.505464

[100 rows x 4 columns]
